name: 'Eleventy Action'
description: 'Build your Eleventy-based static website'
author: 'Richard Herbert'
inputs:
  args:
    description: 'Arguments to pass to the Eleventy invocation'
    required: false
  install_dependencies:
    description: 'If set to `true`, `npm install` will be run before Eleventy is invoked'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
